---
development:
  cloud_name: szulem
  api_key: '111351136877884'
  api_secret: Gy8QuUXKrHfpa4yoIIu3FEvAulA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: szulem
  api_key: '111351136877884'
  api_secret: Gy8QuUXKrHfpa4yoIIu3FEvAulA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: szulem
  api_key: '111351136877884'
  api_secret: Gy8QuUXKrHfpa4yoIIu3FEvAulA
  enhance_image_tag: true
  static_image_support: false
